### ISSUE TITLE
Multimonitor support

### ISSUE THREAD

**Issue by retat** [thiggy01/ubuntu-20.04-change-gdm-background#12]
When I have more than one screen connected, the wallpaper get's stretched to fill both screens. Is it possible to show the same wallpaper on multiple screens?

**Comment by therealestkevin** [comment]
Having a similar problem here with a laptop connected to an external monitor. The external monitor's wallpaper is zoomed in really far while the laptop's wallpaper works perfectly.

**Comment by SolebaySharp** [comment]
I know no one wants to hear this but there [might be a way to make the changes yourselves](https://askubuntu.com/questions/1227070/how-do-i-change-login-screen-theme-or-background-in-ubuntu-20-04), which could potentially circumvent this problem. I bricked my OS doing things I shouldn't and stumbled upon this while trying to work out what I had done. Apologies if you chaps have already seen this. Just make sure you have backups of anything you edit.

**Comment by thiggy01** [comment]
Sorry @retat, I don't have any additional monitor to try to simulate your problem.
Have you tried to uncheck Mirrored Screens on Display Preferences of Ubuntu?
