### ISSUE TITLE
Change backgroudn color?

### ISSUE THREAD

**Issue by SourceSkyBoxer** [thiggy01/ubuntu-20.04-change-gdm-background#2]
Hello dear, can I change for solid color as background? If I don't want add image and I really want change only solid color of background. Is it possible? Thanks for nice small tool!

**Comment by PRATAP-KUMAR** [comment]
https://github.com/PRATAP-KUMAR/focalgdm3 for plain background color you may try this. https://github.com/PRATAP-KUMAR/focalgdm3

**Comment by PRATAP-KUMAR** [comment]
https://github.com/PRATAP-KUMAR/focalgdm3 you may try this..

**Comment by thiggy01** [comment]
Hi @SourceSkyBoxer, Thanks for the suggestion.
This feature is not hard to implemnt as long as you know what css color name or code you want to have.
I'll work on something that will allow the user to type what css color he want to set as gdm background. I'll let you know when it is finished.
