### ISSUE TITLE
./ubuntu-20.04-change-gdm-background: line 71: glib-compile-resources: command not found mv: cannot stat 'gdm3-theme.gresource': No such file or directory GDM background sucessfuly changed. Restart GDM service to apply change. The background did not change on my ubuntu 20.04

### ISSUE THREAD

**Issue by Akash-Rayhan** [thiggy01/ubuntu-20.04-change-gdm-background#3]
sudo ./ubuntu-20.04-change-gdm-background macaw-poly.jpg  at this command the picture and the script are at the home directory

**Comment by mhoangvslev** [comment]
@Akash-Rayhan According to [this](https://github.com/juhaku/loginized/issues/3), you need to install ```libglib2.0-dev-bin``` first. Maybe @thiggy01 can kindly add it into the script.

```sh
sudo apt install libglib2.0-dev-bin
```

**Comment by Akash-Rayhan** [comment]
> @Akash-Rayhan According to [this](https://github.com/juhaku/loginized/issues/3), you need to install `libglib2.0-dev-bin` first. Maybe @thiggy01 can kindly add it into the script.
> 
> ```shell
> sudo apt install libglib2.0-dev-bin
> ```

@mhoangvslev thanks for your comment it works now

**Comment by thiggy01** [comment]
@mhoangvslev you are right.
I added a check for glib lib installation before running the script.
If it's not installed it asks the user if it wants to install it.
