### ISSUE TITLE
File permission

### ISSUE THREAD

**Issue by huepf** [thiggy01/ubuntu-20.04-change-gdm-background#4]
I have been playing around with your script a little but it kept failing on my installation.
Turned out that the file permission of `/usr/share/gnome-shell/gdm3-theme.gresource` had permissions of 640 with root as owner after your script runs.
This resulted in gdm not starting and I ended up in the "oh snap, something went wrong screen".
Obviously the --restore flag wasn't able to fix this problem either.

I had to set permissions to 644.

It might be a good idea to add a `chmod 644 $gdm3Resource` at the end of the script. Just to be save and to save a few users from a serious headache.

**Comment by thiggy01** [comment]
Thanks @huepf for reporting this issue. 
I really don't know what may have caused this permission problem with you.
I'm going to apply your solution to prevent further permission changings.

**Comment by thiggy01** [comment]
Solution applied. Closing issue.
