### ISSUE TITLE
Let us buy you a Ko-Fi

### ISSUE THREAD

**Issue by tachyondecay** [thiggy01/ubuntu-20.04-change-gdm-background#6]
I laboriously changed my background image by editing CSS files in 18.04 about a month or so before upgrading to 20.04. I found your script while Googling for how to accomplish the same thing, and you've made it so much easier! It works great.

I would love to send a few dollars your way via Ko-Fi or a similar platform. Please consider letting us know how we can show our appreciation in the README.

**Comment by thiggy01** [comment]
I'm glad this was useful to you @tachyondecay.
I'm making this work as a hobby and as a way to learn some coding skills.
I just created a Ko-Fi profile and will make sure people have a way to appreciate my work on README.
