### ISSUE TITLE
keep slideshow and just remove the blur

### ISSUE THREAD

**Issue by rubo77** [thiggy01/ubuntu-20.04-change-gdm-background#9]
I have a slideshow running, which is stored in `~/.local/share/shotwell/wallpaper/wallpaper.xml`

This slideshow also takes effect on the lock-screen, but the current picture is **blurred**

How can I just **remove the blur** and see the same slideshow in the lock screen in Ubuntu 20.04 like it already worked fine in 19.10

**Comment by thiggy01** [comment]
Sorry, I can't help with that. 
My script doesn't deal with lockscreen. It just sets an image on login screen.

**Comment by rubo77** [comment]
I found out, there is a Extension called Control Blur Effect on Lock Screen.

See https://askubuntu.com/q/1247024/34298
